nameOverride: iam-controller
fullnameOverride: iam-controller

aws:
  region: "us-east-1"
  endpoint_url: "https://0.0.0.0:4566"

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/ack-iam-controller
